### ISSUE TITLE
Missing some dependencies installation step

### ISSUE THREAD

**Issue by edgarcamilocamacho** [Tiago-Harmonic/tiago_harmonic#4]
Hello.

I fixed the branch problem exposed in #3. But now there are some dependencies that are not defined in the steps, but needed by some of the packages:

```
ros-jazzy-hardware-interface
ros-jazzy-controller-manager-msgs
```

I tried to automatically install dependencies but there are packages that are not properly linked:

```
rosdep install --from-paths src -y --ignore-src
```

Output:

```
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
pal_gripper_simulation: Cannot locate rosdep definition for [pal_gazebo_worlds]
tiago_description: Cannot locate rosdep definition for [urdf_test]
tiago_2dnav: Cannot locate rosdep definition for [pal_maps]
tiago_gazebo: Cannot locate rosdep definition for [pal_gazebo_plugins]
pal_gripper_description: Cannot locate rosdep definition for [urdf_test]
pmb2_description: Cannot locate rosdep definition for [urdf_test]
pmb2_2dnav: Cannot locate rosdep definition for [pal_maps]
omni_base_description: Cannot locate rosdep definition for [urdf_test]
```

**Comment by Juancams** [comment]
Hi!

rosdep gives this error because it is trying to install those packages which are not available for installation in ros. This is a direct fork of the humble branch, so it is normal to get these warnings.

Regarding the packages you had to install by hand, we will add them so that rosdep can install them.
